### ISSUE TITLE
bug: Installation aborted by error: brut.common.BrutException

### ISSUE THREAD

**Issue by jaepil-choi** [kitadai31/revanced-patches-android6-7#27]
### Type

Error while patching

### Bug description

Installation aborted while patching by the below error. 
It's an old Android 7.0 Galaxy tablet without root. 

.apk version was set to recommended version so I wonder where this bug is coming from. 
Although I have 0 knowledge in Android development but it seems like Flutter is the issue judging by the error log? 

### Steps to reproduce

Step 1. Download Youtube apk 17.34.36, download "doctored" version of revanced manager (https://github.com/kitadai31/revanced-manager-android7), install it. 

Step 2. Run the patch as described. 

Step 3. Installation aborted from error. 

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied client-spoof
Applied custom-branding-icon-afn-red
Applied custom-branding-name
Applied custom-seekbar-color
Applied custom-video-speed
Applied default-video-quality
Applied default-video-speed
Applied disable-haptic-feedback
Applied enable-external-browser
Applied enable-minimized-playback
Applied enable-old-quality-layout
Applied enable-open-links-directly
Applied enable-seekbar-tapping
Applied enable-tablet-miniplayer
Applied enable-wide-searchbar
Applied force-vp9-codec
Applied header-switch
Applied hide-auto-captions
Applied hide-auto-player-popup-panels
Applied hide-autoplay-button
Applied hide-button-container
Applied hide-cast-button
Applied hide-channel-watermark
Applied hide-comment-component
Applied hide-create-button
Applied hide-crowdfunding-box
Applied hide-email-address
Applied hide-endscreen-cards
Applied hide-endscreen-overlay
Applied hide-filmstrip-overlay
Applied hide-firsttime-background-notification
Applied hide-flyout-panel
Applied hide-fullscreen-panels
Applied hide-general-ads
Applied hide-info-cards
Applied hide-live-chat-button
Applied hide-mix-playlists
Applied hide-next-prev-button
Applied hide-player-captions-button
Applied hide-player-overlay-filter
Applied hide-shorts-button
Applied hide-shorts-component
Applied hide-shorts-navbar
Applied hide-snackbar
Applied hide-startup-shorts-player
Applied hide-stories
Applied hide-suggested-actions
Applied hide-time-and-seekbar
Applied hide-tooltip-content
Applied hide-video-ads
Applied layout-switch
Applied microg-support
Applied optimize-resource
Applied overlay-buttons
Applied patch-options
Applied protobuf-spoof
Applied remove-player-button-background
Applied return-youtube-dislike
Applied settings
Applied sponsorblock
Applied spoof-app-version
Applied swipe-controls
Applied switch-create-notification
Applied theme
Applied translations
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-1/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EPDIST/cache/aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 33, --version-code, 1531307456, --version-name, 17.34.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL2086292632.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EPDIST/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EPDIST/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EPDIST/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:212)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp0(MainActivity.kt)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at java.lang.Thread.run(Thread.java:762)
Caused by: brut.common.BrutException: could not exec (exit code = 135): [/data/app/app.revanced.manager.flutter-1/lib/arm/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EPDIST/cache/aapt_temp_file, --min-sdk-version, 23, --target-sdk-version, 33, --version-code, 1531307456, --version-name, 17.34.36, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL2086292632.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EPDIST/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EPDIST/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EPDIST/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Device Environment

Android 7.0 
Samsung Galaxy Tab S2 (last update was 2018.1) 
non-root. 

Youtube Vanced ran fine until recently. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
The cause is ARMv7.
Manager does not support ARMv7 (32bit) devices.
Please use another device or PC.

**Comment by jaepil-choi** [comment]
@kitadai31 Thank you. Didn't think mobile cpu could be the culprit.
