### ISSUE TITLE
bug: Crash on launch, even with only client spoof and branding patches

### ISSUE THREAD

**Issue by Mrcubix** [kitadai31/revanced-patches-android6-7#42]
### Type

Error at runtime

### Bug description

App crash on second launch, after first launch restart

### Steps to reproduce

1. Build revanced with just client spoof and custom branding patches enabled
2. Install the app manually or using revanced-builder whenever it wants to work
3. launch the app
4. On first launch, there is a message box about it being the first launch for a couple seconds before restarting, and then crash.

### Relevant log output

```shell
### adb logcat -s Youtube

08-12 23:17:32.698  6940  6940 W YouTube : Forcefully created overlay:hrr@594fcbc helper:Lazy@ad91445 view:null status: ....... {...}
08-12 23:17:32.707  6940  6940 W YouTube : Forcefully created overlay:iir@77cd366 helper:Lazy@f7346a7 view:null status: ....... {✓..}
08-12 23:17:32.969  6940  6972 W ResourceType: Requesting resource 0x7f040901 failed because it is complex
08-12 23:17:33.199  6940  6940 I Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
08-12 23:17:33.274  6940  6940 W YT.MDX.BaseBackgroundSc: Client LivingRoomNotificationRequestManager attempted to notify configuration change when it hasn't been registered.
08-12 23:17:33.275  6940  6940 W YT.MDX.BaseBackgroundSc: Client LivingRoomNotificationRevokeManager attempted to notify configuration change when it hasn't been registered.
08-12 23:17:33.545  6940  6940 E Auth    : [GoogleAuthUtil] Exception when getting accounts
08-12 23:17:33.545  6940  6940 E Auth    : java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.google.android.youtube, sha256=[dc11939a8a54e05c3f27771ddc7d69f31b9bb62ff201b93c3ffe161f0cc6db3d], atk=true, ver=233013015.true (go/gsrlt)
08-12 23:17:33.545  6940  6940 E Auth    :      at android.os.Parcel.readException(Parcel.java:1684)
08-12 23:17:33.545  6940  6940 E Auth    :      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
08-12 23:17:33.545  6940  6940 E Auth    :      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-12 23:17:33.545  6940  6940 E Auth    :      at android.content.ContentProviderProxy.call(ContentProviderNative.java:646)
08-12 23:17:33.545  6940  6940 E Auth    :      at android.content.ContentProviderClient.call(ContentProviderClient.java:456)
08-12 23:17:33.545  6940  6940 E Auth    :      at lxi.m(PG:8)
08-12 23:17:33.545  6940  6940 E Auth    :      at qve.d(PG:1)
08-12 23:17:33.545  6940  6940 E Auth    :      at qyd.i(PG:1)
08-12 23:17:33.545  6940  6940 E Auth    :      at qxf.rq(PG:10)
08-12 23:17:33.545  6940  6940 E Auth    :      at qxf.b(PG:2)
08-12 23:17:33.545  6940  6940 E Auth    :      at kzi.u(PG:26)
08-12 23:17:33.545  6940  6940 E Auth    :      at kzi.p(PG:1)
08-12 23:17:33.545  6940  6940 E Auth    :      at kzi.d(PG:3)
08-12 23:17:33.545  6940  6940 E Auth    :      at adqa.b(PG:22)
08-12 23:17:33.545  6940  6940 E Auth    :      at admk.run(PG:57)
08-12 23:17:33.545  6940  6940 E Auth    :      at adzw.run(PG:2)
08-12 23:17:33.545  6940  6940 E Auth    :      at android.os.Handler.handleCallback(Handler.java:751)
08-12 23:17:33.545  6940  6940 E Auth    :      at android.os.Handler.dispatchMessage(Handler.java:95)
08-12 23:17:33.545  6940  6940 E Auth    :      at android.os.Looper.loop(Looper.java:154)
08-12 23:17:33.545  6940  6940 E Auth    :      at android.app.ActivityThread.main(ActivityThread.java:6186)
08-12 23:17:33.545  6940  6940 E Auth    :      at java.lang.reflect.Method.invoke(Native Method)
08-12 23:17:33.545  6940  6940 E Auth    :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-12 23:17:33.545  6940  6940 E Auth    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-12 23:17:33.619  6940  6940 E skd     : No overlay to dismiss.
08-12 23:17:33.633  6940  6940 E YouTube : Null interactionLoggingScreen found when removeInteractionLoggingScreen.
08-12 23:17:33.670  6940  6977 E Auth    : [GoogleAuthUtil] Exception when getting accounts
08-12 23:17:33.670  6940  6977 E Auth    : java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.google.android.youtube, sha256=[dc11939a8a54e05c3f27771ddc7d69f31b9bb62ff201b93c3ffe161f0cc6db3d], atk=true, ver=233013015.true (go/gsrlt)
08-12 23:17:33.670  6940  6977 E Auth    :      at android.os.Parcel.readException(Parcel.java:1684)
08-12 23:17:33.670  6940  6977 E Auth    :      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
08-12 23:17:33.670  6940  6977 E Auth    :      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-12 23:17:33.670  6940  6977 E Auth    :      at android.content.ContentProviderProxy.call(ContentProviderNative.java:646)
08-12 23:17:33.670  6940  6977 E Auth    :      at android.content.ContentProviderClient.call(ContentProviderClient.java:456)
08-12 23:17:33.670  6940  6977 E Auth    :      at lxi.m(PG:8)
08-12 23:17:33.670  6940  6977 E Auth    :      at qve.d(PG:1)
08-12 23:17:33.670  6940  6977 E Auth    :      at qyd.i(PG:1)
08-12 23:17:33.670  6940  6977 E Auth    :      at qyd.h(PG:1)
08-12 23:17:33.670  6940  6977 E Auth    :      at qvv.run(PG:23)
08-12 23:17:33.670  6940  6977 E Auth    :      at nsk.run(PG:5)
08-12 23:17:33.670  6940  6977 E Auth    :      at nso.run(PG:23)
08-12 23:17:33.670  6940  6977 E Auth    :      at ntg.run(PG:62)
08-12 23:17:33.670  6940  6977 E Auth    :      at mwy.run(PG:7)
08-12 23:17:33.670  6940  6977 E Auth    :      at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
08-12 23:17:33.670  6940  6977 E Auth    :      at java.lang.Thread.run(Thread.java:761)
08-12 23:17:33.737  6940  6972 E Auth    : [GoogleAuthUtil] Exception when getting accounts
08-12 23:17:33.737  6940  6972 E Auth    : java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.google.android.youtube, sha256=[dc11939a8a54e05c3f27771ddc7d69f31b9bb62ff201b93c3ffe161f0cc6db3d], atk=true, ver=233013015.true (go/gsrlt)
08-12 23:17:33.737  6940  6972 E Auth    :      at android.os.Parcel.readException(Parcel.java:1684)
08-12 23:17:33.737  6940  6972 E Auth    :      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
08-12 23:17:33.737  6940  6972 E Auth    :      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-12 23:17:33.737  6940  6972 E Auth    :      at android.content.ContentProviderProxy.call(ContentProviderNative.java:646)
08-12 23:17:33.737  6940  6972 E Auth    :      at android.content.ContentProviderClient.call(ContentProviderClient.java:456)
08-12 23:17:33.737  6940  6972 E Auth    :      at lxi.m(PG:8)
08-12 23:17:33.737  6940  6972 E Auth    :      at qve.d(PG:1)
08-12 23:17:33.737  6940  6972 E Auth    :      at qyd.i(PG:1)
08-12 23:17:33.737  6940  6972 E Auth    :      at qyd.j(PG:1)
08-12 23:17:33.737  6940  6972 E Auth    :      at qsv.run(PG:1)
08-12 23:17:33.737  6940  6972 E Auth    :      at nsk.run(PG:5)
08-12 23:17:33.737  6940  6972 E Auth    :      at nso.run(PG:23)
08-12 23:17:33.737  6940  6972 E Auth    :      at ntg.run(PG:62)
08-12 23:17:33.737  6940  6972 E Auth    :      at mwy.run(PG:7)
08-12 23:17:33.737  6940  6972 E Auth    :      at com.google.android.apps.youtube.embeddedplayer.service.jar.client.r.run(PG:5)
08-12 23:17:33.737  6940  6972 E Auth    :      at java.lang.Thread.run(Thread.java:761)
08-12 23:17:33.757  6940  6940 W View    : requestLayout() improperly called by android.widget.FrameLayout{e43914a V.E...... ......ID 0,60-800,1250 #7f0b0b28 app:id/pane_fragment_container} during layout: running second layout pass
08-12 23:17:33.866  6940  6940 W ResourceType: Requesting resource 0x7f040901 failed because it is complex
08-12 23:17:33.891  6940  6940 W YouTube : Failed to set parent screen
08-12 23:17:33.939  6940  6975 E YouTube : There was an error
08-12 23:17:33.939  6940  6975 E YouTube : ctz
08-12 23:17:33.939  6940  6975 E YouTube :      at qtw.run(PG:49)
08-12 23:17:33.939  6940  6975 E YouTube :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-12 23:17:33.939  6940  6975 E YouTube :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-12 23:17:33.939  6940  6975 E YouTube :      at sdi.run(PG:58)
08-12 23:17:33.939  6940  6975 E YouTube :      at java.lang.Thread.run(Thread.java:761)
08-12 23:17:33.964  6940  6951 I art     : Background sticky concurrent mark sweep GC freed 43910(2MB) AllocSpace objects, 38(1660KB) LOS objects, 8% free, 47MB/52MB, paused 8.544ms total 279.296ms
08-12 23:17:34.740  6940  6945 I art     : Do full code cache collection, code=1256KB, data=1516KB
08-12 23:17:34.764  6940  6945 I art     : Waiting for a blocking GC JitCodeCache
08-12 23:17:35.184  6940  7082 W art     : Long monitor contention with owner cronet-glide-http-request-queue27-1 (7072) at int libcore.io.Posix.writeBytes(java.io.FileDescriptor, java.lang.Object, int, int)(Posix.java:-2) waiters=0 in cua sxq.a(java.lang.String) for 355ms
08-12 23:17:35.196  6940  7083 W art     : Long monitor contention with owner cronet-glide-http-request-queue27-1 (7072) at int libcore.io.Posix.writeBytes(java.io.FileDescriptor, java.lang.Object, int, int)(Posix.java:-2) waiters=1 in cua sxq.a(java.lang.String) for 211ms
08-12 23:17:35.310  6940  6951 I art     : Background partial concurrent mark sweep GC freed 98138(4MB) AllocSpace objects, 48(1976KB) LOS objects, 25% free, 47MB/63MB, paused 7.110ms total 544.036ms
08-12 23:17:35.310  6940  6945 I art     : WaitForGcToComplete blocked for 545.928ms for cause JitCodeCache
08-12 23:17:35.310  6940  6945 I art     : Starting a blocking GC JitCodeCache
08-12 23:17:35.312  6940  6945 I art     : After code cache collection, code=1215KB, data=1117KB
08-12 23:17:35.360  6940  7083 W art     : Long monitor contention with owner cronet-glide-http-request-queue27-2 (7073) at void sxq.d(java.lang.String, cua)(PG:-1) waiters=0 in cua sxq.a(java.lang.String) for 129ms
08-12 23:17:35.666  6940  6940 E YouTube : Failed to fetch kids onboarding status, finishing the App.
08-12 23:17:35.745  6940  6940 I Choreographer: Skipped 102 frames!  The application may be doing too much work on its main thread.
08-12 23:17:36.095  6940  6980 W art     : Long monitor contention with owner ChromiumNet (7016) at void org.chromium.net.impl.CronetUrlRequestContext.onRttObservation(int, long, int)(PG:1) waiters=0 in int org.chromium.net.impl.CronetUrlRequestContext.getEffectiveConnectionType() for 131ms
08-12 23:17:36.617  6940  6940 W YT.mlplayer: Stayawake OFF
08-12 23:17:37.364  6940  6980 W art     : Long monitor contention with owner BG Thread #8 (6974) at void afsl.c(int, ageq)(PG:-1) waiters=0 in sqx ysb.a() for 735ms
08-12 23:17:37.375  6940  6973 W art     : Long monitor contention with owner BG Thread #8 (6974) at void afsl.c(int, ageq)(PG:-1) waiters=1 in void ysb.g(agfo) for 704ms
08-12 23:17:37.680  6940  6973 W art     : Long monitor contention with owner BG Thread #13 (6980) at boolean yro.t(aigl)(PG:1) waiters=0 in void yro.g(aigl) for 244ms

### AndroidRuntime

nothing of interest
```

### Additional context

Built using revanced builder.

### Device Environment

Android 7.1.1
32 bits arm CPU

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kitadai31** [comment]
MicroG is installed properly?

**Comment by Mrcubix** [comment]
vanced works fine (other than the recent buffering issue for videos +1 min in length), so afaik, yes

not that it should matter anyway since it does the same with a rooted install

**Comment by kitadai31** [comment]
Starting to [Patches v5.2.1](https://github.com/kitadai31/revanced-patches-android6-7/releases/tag/v5.2.1) (released in January 2025), RVX for A6-7 is based on the latest RVX.
All problems that existed in old v2.160.x versions have probably been resolved.
Therefore, I'm closing all issues opened in v2.160.x.
