### ISSUE TITLE
bug: Error during patching using ReVanced Manager, aborting at the "decoding resources" stage

### ISSUE THREAD

**Issue by megascorcher** [kitadai31/revanced-patches-android6-7#43]
### Type

Error while patching

### Bug description

Just started getting the issue with spoofer today, making any video buffer forever at the 1 minute 9 seconds mark. Read through reddit posts that there was an update. Tried updating/repatching using v17.34.36 APK file, update aborting almost immediately due to an error that I do not comprehend.

### Steps to reproduce

1: Open ReVanced Manager
2: Go to Patcher and select application
3: Press "Storage", select APK for v17.34.36
4: Select Recommended Patches
5: Press "Patch"
6: Error occurs seconds after it gets to the "Decoding resources" stage

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred! Aborting
Error:
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:321)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$kxvfcFiIKARIH6oxYjk9gWWxjp0(MainActivity.kt)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at java.lang.Thread.run(Thread.java:776)
Caused by: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/Integer;Ljava/lang/Iterable;Ljava/lang/Iterable;Ljava/lang/Iterable;Lkotlin/jvm/functions/Function2;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lapp/revanced/patcher/fingerprint/method/impl/MethodFingerprint; or its super classes (declaration of 'app.revanced.patcher.fingerprint.method.impl.MethodFingerprint' appears in base.apk)
	at app.revanced.patches.youtube.misc.clientspoof.bytecode.fingerprints.UserAgentHeaderBuilderFingerprint.<init>(UserAgentHeaderBuilderFingerprint.kt:6)
	at app.revanced.patches.youtube.misc.clientspoof.bytecode.fingerprints.UserAgentHeaderBuilderFingerprint.<clinit>(UserAgentHeaderBuilderFingerprint.kt)
	at app.revanced.patches.youtube.misc.clientspoof.bytecode.patch.ClientSpoofBytecodePatch.<init>(ClientSpoofBytecodePatch.kt:19)
	... 12 more
```

### Solution

ReVanced Manager was out of date, needed update through its own APK. Patched successfully with new version of ReVanced Manager.

### Device Environment

Android 7.0 on Huawei P9 (EVA-L09)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by megascorcher** [comment]
I recognize now that this could be an issue with the ReVanced Manager and not the patch source, I have absolutely no idea as I don't know what to glean from the error messages. I have tried to find what the "12 more" entail but no log I save includes that part.

**Comment by kitadai31** [comment]
Update ReVanced Manager

**Comment by megascorcher** [comment]
You know, it should have clued me onto it when the recent instructions for updating said the Patcher in the ReVanced Manager said to press the "Default" option for patches while on my version it said "Recommended". I was not aware there was an update to ReVanced Manager as it doesn't seem the in-app updater is working or can inform me of new versions. Updated it through APK, ran the patch successfully, my ReVanced Extended works as it did before now. Thank you very much.
